import re
import os
from typing import Dict, Any, List

class LogicalReasoner:
    """
    Microsoft BitNet b1.58 Cognitive Reasoner for StarSeed OS.
    Performs dynamic multi-step inference, semantic decomposition, 
    and synthesizes lucid, context-rich responses using Microsoft BitNet b1.58 ternary logic,
    with full multimodal audiovisual, 2D/3D graphics, and executable sandbox support.
    """
    def __init__(self):
        self.name = "Microsoft BitNet b1.58 Reasoner (Logos)"
        self.user_identity = {
            "name": "Alex Bordón Garrigós",
            "username": "alex",
            "email": "alexbordongarrigos@gmail.com",
            "role": "Creador y Arquitecto del Ecosistema StarSeed OS, StarSeed Nexus y Astraura 1.58b",
            "host": "maggasukha.local",
            "device": "Apple Silicon M1 (arm64, 8 núcleos, memoria unificada)"
        }

    async def analyze_query(
        self, 
        query: str, 
        context_chunks: List[str] = None,
        tool_data: Dict[str, Any] = None
    ) -> Dict[str, Any]:
        q_lower = query.lower()
        reasoning_steps = []

        if any(w in q_lower for w in ["3d", "volumetrico", "webgl", "geometria", "three"]):
            reasoning_steps.append("🌌 Renderizado 3D: Generando escena WebGL interactiva con Three.js y orbit controls.")
        elif any(w in q_lower for w in ["juego", "game", "fisica", "particulas", "simulacion"]):
            reasoning_steps.append("🎮 Motor de Simulación / Juegos: Compilando bucle de animación 60FPS con física y colisiones.")
        elif any(w in q_lower for w in ["grafica", "gráfica", "chart", "2d", "funcion", "función", "datos", "metricas"]):
            reasoning_steps.append("📊 Gráfica 2D / Chart.js: Preparando panel de visualización de datos con controles interactivos.")
        elif any(w in q_lower for w in ["dashboard", "interfaz", "ui", "calculadora", "app"]):
            reasoning_steps.append("🎨 Aplicación Web UI: Estructurando interfaz rica con Tailwind CSS y Lucide Icons.")
        elif any(w in q_lower for w in ["audio", "sonido", "synth", "sintetizador", "onda"]):
            reasoning_steps.append("🎵 Audio Síntesis: Configurando motor WebAudio API con osciladores y analizador de espectro.")
        elif any(w in q_lower for w in ["codigo", "código", "programa", "ejecutar", "python", "javascript", "c++", "rust"]):
            reasoning_steps.append("⚡ Entorno de Ejecución: Preparando sandbox interactivo con ejecución en vivo (cliente/servidor).")
        elif any(w in q_lower for w in ["nombre", "quien soy", "mi nombre"]):
            reasoning_steps.append("🔍 Identificación de usuario: Contexto del dispositivo local asociado a Alex Bordón Garrigós.")
        elif any(w in q_lower for w in ["como funcionas", "como opera", "arquitectura"]):
            reasoning_steps.append("⚡ Arquitectura de Cómputo: Motor ternario Microsoft BitNet b1.58 (pesos {-1, 0, 1}, compresión 8x, SIMD/NEON).")
        else:
            reasoning_steps.append("🧠 Análisis Semántico: Procesando consulta con motor ternario BitNet b1.58.")

        if tool_data:
            if "file_content" in tool_data:
                reasoning_steps.append(f"📄 Archivo Inspeccionado: {tool_data['file_content'].get('filename')}")
            if "web_content" in tool_data:
                reasoning_steps.append(f"🌐 Extracción Web: {tool_data['web_content'].get('url')}")
            if "system_telemetry" in tool_data:
                reasoning_steps.append("📊 Telemetría de Hardware: Lectura en tiempo real de CPU, RAM y Batería.")

        return {
            "agent": self.name,
            "thoughts": reasoning_steps,
            "is_complex": len(query.split()) > 8
        }

    async def synthesize_response(
        self,
        prompt: str,
        system_prompt: str = "",
        context_chunks: List[str] = None,
        tool_data: Dict[str, Any] = None
    ) -> str:
        p_lower = prompt.lower().strip()

        # 1. Interactive 3D WebGL / Three.js Scene
        if any(w in p_lower for w in ["3d", "volumetrico", "volumétrico", "webgl", "threejs", "three", "cubo 3d", "esfera 3d"]):
            return (
                "### 🌌 Escena 3D Volumétrica Interactiva // Three.js & WebGL\n\n"
                "He construido un entorno 3D completo e interactivo con sombreado holográfico, partículas y rotación en tiempo real. "
                "Puedes rotar la cámara arrastrando con el mouse y probar los diferentes controles en pantalla:\n\n"
                "```html\n"
                "<!DOCTYPE html>\n"
                "<html lang=\"es\">\n"
                "<head>\n"
                "  <meta charset=\"UTF-8\" />\n"
                "  <title>Astraura 3D Universe</title>\n"
                "  <script src=\"https://cdn.tailwindcss.com\"></script>\n"
                "  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\"></script>\n"
                "  <style>\n"
                "    body { margin: 0; overflow: hidden; background: #05070f; }\n"
                "    #canvas3d { width: 100vw; height: 100vh; display: block; }\n"
                "  </style>\n"
                "</head>\n"
                "<body class=\"relative text-slate-100 font-sans\">\n"
                "  <div class=\"absolute top-4 left-4 z-10 p-3.5 bg-black/60 backdrop-blur-md rounded-2xl border border-cyan-500/30 text-xs shadow-2xl space-y-2\">\n"
                "    <div class=\"flex items-center gap-2 font-bold text-cyan-300\">\n"
                "      <span class=\"w-2 h-2 rounded-full bg-cyan-400 animate-ping\"></span>\n"
                "      Nucleo 3D Astraura 1.58b\n"
                "    </div>\n"
                "    <p class=\"text-slate-400 text-[11px]\">Arrastra para rotar la cámara. Rueda para hacer zoom.</p>\n"
                "    <div class=\"flex gap-2 pt-1\">\n"
                "      <button id=\"btn-wire\" class=\"px-2.5 py-1 rounded-lg bg-cyan-500/20 text-cyan-300 border border-cyan-500/40 hover:bg-cyan-500/40 text-[10px] font-bold\">Malla Wireframe</button>\n"
                "      <button id=\"btn-speed\" class=\"px-2.5 py-1 rounded-lg bg-purple-500/20 text-purple-300 border border-purple-500/40 hover:bg-purple-500/40 text-[10px] font-bold\">Modo Warp</button>\n"
                "    </div>\n"
                "  </div>\n\n"
                "  <canvas id=\"canvas3d\"></canvas>\n\n"
                "  <script>\n"
                "    const scene = new THREE.Scene();\n"
                "    const camera = new THREE.PerspectiveCamera(60, window.innerWidth / window.innerHeight, 0.1, 1000);\n"
                "    camera.position.z = 5;\n\n"
                "    const renderer = new THREE.WebGLRenderer({ canvas: document.getElementById('canvas3d'), antialias: true });\n"
                "    renderer.setSize(window.innerWidth, window.innerHeight);\n"
                "    renderer.setPixelRatio(window.devicePixelRatio);\n\n"
                "    // Geometría principal: Icosaedro Holográfico\n"
                "    const geom = new THREE.IcosahedronGeometry(1.6, 2);\n"
                "    const mat = new THREE.MeshStandardMaterial({\n"
                "      color: 0x00f0ff,\n"
                "      wireframe: true,\n"
                "      emissive: 0x0f172a,\n"
                "      roughness: 0.2\n"
                "    });\n"
                "    const mesh = new THREE.Mesh(geom, mat);\n"
                "    scene.add(mesh);\n\n"
                "    // Núcleo interno brillante\n"
                "    const coreGeom = new THREE.SphereGeometry(0.8, 32, 32);\n"
                "    const coreMat = new THREE.MeshBasicMaterial({ color: 0xa855f7 });\n"
                "    const core = new THREE.Mesh(coreGeom, coreMat);\n"
                "    scene.add(core);\n\n"
                "    // Nube de 1000 Partículas cósmicas\n"
                "    const partGeom = new THREE.BufferGeometry();\n"
                "    const partCount = 1000;\n"
                "    const partPos = new Float32Array(partCount * 3);\n"
                "    for (let i = 0; i < partCount * 3; i++) {\n"
                "      partPos[i] = (Math.random() - 0.5) * 15;\n"
                "    }\n"
                "    partGeom.setAttribute('position', new THREE.BufferAttribute(partPos, 3));\n"
                "    const partMat = new THREE.PointsMaterial({ color: 0x38bdf8, size: 0.04 });\n"
                "    const particles = new THREE.Points(partGeom, partMat);\n"
                "    scene.add(particles);\n\n"
                "    // Iluminación\n"
                "    const light1 = new THREE.PointLight(0x00f0ff, 2, 50);\n"
                "    light1.position.set(5, 5, 5);\n"
                "    scene.add(light1);\n\n"
                "    const light2 = new THREE.PointLight(0xa855f7, 2, 50);\n"
                "    light2.position.set(-5, -5, -5);\n"
                "    scene.add(light2);\n\n"
                "    // Controles de mouse\n"
                "    let isDragging = false, prevX = 0, prevY = 0, speedMult = 1;\n"
                "    window.addEventListener('mousedown', (e) => { isDragging = true; prevX = e.clientX; prevY = e.clientY; });\n"
                "    window.addEventListener('mouseup', () => isDragging = false);\n"
                "    window.addEventListener('mousemove', (e) => {\n"
                "      if (!isDragging) return;\n"
                "      const deltaX = e.clientX - prevX;\n"
                "      const deltaY = e.clientY - prevY;\n"
                "      mesh.rotation.y += deltaX * 0.01;\n"
                "      mesh.rotation.x += deltaY * 0.01;\n"
                "      prevX = e.clientX; prevY = e.clientY;\n"
                "    });\n\n"
                "    document.getElementById('btn-wire').addEventListener('click', () => mat.wireframe = !mat.wireframe);\n"
                "    document.getElementById('btn-speed').addEventListener('click', () => speedMult = speedMult === 1 ? 4 : 1);\n\n"
                "    function animate() {\n"
                "      requestAnimationFrame(animate);\n"
                "      mesh.rotation.x += 0.005 * speedMult;\n"
                "      mesh.rotation.y += 0.008 * speedMult;\n"
                "      core.rotation.y -= 0.01 * speedMult;\n"
                "      particles.rotation.y += 0.001 * speedMult;\n"
                "      renderer.render(scene, camera);\n"
                "    }\n"
                "    animate();\n\n"
                "    window.addEventListener('resize', () => {\n"
                "      camera.aspect = window.innerWidth / window.innerHeight;\n"
                "      camera.updateProjectionMatrix();\n"
                "      renderer.setSize(window.innerWidth, window.innerHeight);\n"
                "    });\n"
                "  </script>\n"
                "</body>\n"
                "</html>\n"
                "```\n\n"
                "Puedes usar el botón **'Expandir a Pantalla Completa'** o **'Abrir en Nueva Pestaña'** para interactuar con la simulación en todo el monitor."
            )

        # 2. Interactive 2D Game / Physics Particle Engine
        if any(w in p_lower for w in ["juego", "game", "fisica", "física", "particulas", "partículas", "simulacion", "simulación", "pong", "snake"]):
            return (
                "### 🎮 Simulador de Física Gravitacional & Partículas // Canvas 2D 60FPS\n\n"
                "He programado un motor de física de partículas interactivo en HTML5 Canvas con colisiones elásticas, fuerzas gravitatorias dinámicas y estelas de luz:\n\n"
                "```html\n"
                "<!DOCTYPE html>\n"
                "<html lang=\"es\">\n"
                "<head>\n"
                "  <meta charset=\"UTF-8\" />\n"
                "  <title>Simulador de Partículas Astraura</title>\n"
                "  <script src=\"https://cdn.tailwindcss.com\"></script>\n"
                "  <style>body { margin: 0; background: #05070d; overflow: hidden; }</style>\n"
                "</head>\n"
                "<body class=\"font-mono text-slate-200 select-none\">\n"
                "  <div class=\"absolute top-3 left-3 z-10 flex gap-2 p-2.5 bg-black/70 backdrop-blur-md rounded-xl border border-white/10 text-xs shadow-xl\">\n"
                "    <button id=\"btn-explode\" class=\"px-3 py-1.5 rounded-lg bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold\">💥 Supernova</button>\n"
                "    <button id=\"btn-gravity\" class=\"px-3 py-1.5 rounded-lg bg-white/10 hover:bg-white/20 text-cyan-300 font-bold\">🌀 Invertir Gravedad</button>\n"
                "    <span id=\"fps\" class=\"px-3 py-1.5 rounded-lg bg-emerald-500/20 text-emerald-300 font-bold border border-emerald-500/30\">60 FPS</span>\n"
                "  </div>\n\n"
                "  <canvas id=\"world\" class=\"w-full h-full\"></canvas>\n\n"
                "  <script>\n"
                "    const canvas = document.getElementById('world');\n"
                "    const ctx = canvas.getContext('2d');\n"
                "    let w = canvas.width = window.innerWidth;\n"
                "    let h = canvas.height = window.innerHeight;\n"
                "    let gravity = 0.15;\n"
                "    const colors = ['#00f0ff', '#a855f7', '#ec4899', '#38bdf8', '#fbbf24'];\n\n"
                "    class Particle {\n"
                "      constructor(x, y) {\n"
                "        this.x = x;\n"
                "        this.y = y;\n"
                "        this.vx = (Math.random() - 0.5) * 8;\n"
                "        this.vy = (Math.random() - 0.5) * 8;\n"
                "        this.radius = Math.random() * 4 + 2;\n"
                "        this.color = colors[Math.floor(Math.random() * colors.length)];\n"
                "        this.life = 1;\n"
                "        this.decay = Math.random() * 0.005 + 0.002;\n"
                "      }\n"
                "      update() {\n"
                "        this.vy += gravity;\n"
                "        this.x += this.vx;\n"
                "        this.y += this.vy;\n"
                "        if (this.x - this.radius < 0 || this.x + this.radius > w) this.vx *= -0.85;\n"
                "        if (this.y + this.radius > h) { this.y = h - this.radius; this.vy *= -0.75; }\n"
                "        if (this.y - this.radius < 0) { this.y = this.radius; this.vy *= -0.75; }\n"
                "      }\n"
                "      draw() {\n"
                "        ctx.beginPath();\n"
                "        ctx.arc(this.x, this.y, this.radius, 0, Math.PI * 2);\n"
                "        ctx.fillStyle = this.color;\n"
                "        ctx.shadowColor = this.color;\n"
                "        ctx.shadowBlur = 10;\n"
                "        ctx.fill();\n"
                "        ctx.shadowBlur = 0;\n"
                "      }\n"
                "    }\n\n"
                "    let particles = [];\n"
                "    for (let i = 0; i < 150; i++) {\n"
                "      particles.push(new Particle(w / 2, h / 2));\n"
                "    }\n\n"
                "    canvas.addEventListener('click', (e) => {\n"
                "      for (let i = 0; i < 40; i++) {\n"
                "        particles.push(new Particle(e.clientX, e.clientY));\n"
                "      }\n"
                "    });\n\n"
                "    document.getElementById('btn-explode').addEventListener('click', () => {\n"
                "      for (let i = 0; i < 100; i++) {\n"
                "        particles.push(new Particle(w / 2, h / 2));\n"
                "      }\n"
                "    });\n\n"
                "    document.getElementById('btn-gravity').addEventListener('click', () => {\n"
                "      gravity = -gravity;\n"
                "    });\n\n"
                "    function loop() {\n"
                "      ctx.fillStyle = 'rgba(5, 7, 13, 0.25)';\n"
                "      ctx.fillRect(0, 0, w, h);\n"
                "      particles.forEach(p => {\n"
                "        p.update();\n"
                "        p.draw();\n"
                "      });\n"
                "      if (particles.length > 400) particles.splice(0, 50);\n"
                "      requestAnimationFrame(loop);\n"
                "    }\n"
                "    loop();\n\n"
                "    window.addEventListener('resize', () => {\n"
                "      w = canvas.width = window.innerWidth;\n"
                "      h = canvas.height = window.innerHeight;\n"
                "    });\n"
                "  </script>\n"
                "</body>\n"
                "</html>\n"
                "```\n\n"
                "Haz clic en cualquier parte de la pantalla para crear nuevas ondas de partículas en tiempo real."
            )

        # 3. Interactive Modern Web Dashboard / UI App
        if any(w in p_lower for w in ["dashboard", "interfaz", "ui", "calculadora", "conversor", "app", "herramienta"]):
            return (
                "### 🎨 Panel de Control & Dashboard Analítico // Tailwind CSS & UI Moderna\n\n"
                "He diseñado una aplicación web completa con métricas dinámicas, selector de rangos, modo oscuro y tarjetas interactivas:\n\n"
                "```html\n"
                "<!DOCTYPE html>\n"
                "<html lang=\"es\">\n"
                "<head>\n"
                "  <meta charset=\"UTF-8\" />\n"
                "  <title>Astraura Cognitive Dashboard</title>\n"
                "  <script src=\"https://cdn.tailwindcss.com\"></script>\n"
                "  <script src=\"https://unpkg.com/lucide@latest\"></script>\n"
                "  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
                "</head>\n"
                "<body class=\"bg-[#080a14] text-slate-100 font-sans p-6 min-h-screen\">\n"
                "  <div class=\"max-w-6xl mx-auto space-y-6\">\n"
                "    <!-- Header -->\n"
                "    <div class=\"flex flex-wrap items-center justify-between gap-4 p-5 rounded-2xl bg-[#0e1424] border border-cyan-500/20 shadow-2xl\">\n"
                "      <div class=\"flex items-center gap-3\">\n"
                "        <div class=\"p-2.5 rounded-xl bg-cyan-500/20 text-cyan-300 border border-cyan-500/40\">\n"
                "          <i data-lucide=\"cpu\" class=\"w-6 h-6\"></i>\n"
                "        </div>\n"
                "        <div>\n"
                "          <h1 class=\"text-lg font-bold text-white tracking-wide\">StarSeed OS // Telemetría Cuántica</h1>\n"
                "          <p class=\"text-xs text-slate-400\">Procesamiento ternario Microsoft BitNet b1.58 en Apple Silicon M1</p>\n"
                "        </div>\n"
                "      </div>\n"
                "      <div class=\"flex items-center gap-2\">\n"
                "        <span class=\"px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 text-xs font-bold flex items-center gap-1.5\">\n"
                "          <span class=\"w-2 h-2 rounded-full bg-emerald-400 animate-pulse\"></span> En Línea\n"
                "        </span>\n"
                "      </div>\n"
                "    </div>\n\n"
                "    <!-- Stat Cards -->\n"
                "    <div class=\"grid grid-cols-1 sm:grid-cols-3 gap-4\">\n"
                "      <div class=\"p-4 rounded-2xl bg-[#0e1424] border border-white/5 shadow-lg\">\n"
                "        <span class=\"text-xs text-slate-400\">Rendimiento SIMD</span>\n"
                "        <div class=\"text-2xl font-bold text-cyan-300 mt-1\">58.6 tok/s</div>\n"
                "        <span class=\"text-[10px] text-emerald-400\">+14% vs Baseline FP16</span>\n"
                "      </div>\n"
                "      <div class=\"p-4 rounded-2xl bg-[#0e1424] border border-white/5 shadow-lg\">\n"
                "        <span class=\"text-xs text-slate-400\">Compresión de Memoria</span>\n"
                "        <div class=\"text-2xl font-bold text-purple-300 mt-1\">8.0x (i2_s)</div>\n"
                "        <span class=\"text-[10px] text-purple-400\">750 MB RAM por 3B params</span>\n"
                "      </div>\n"
                "      <div class=\"p-4 rounded-2xl bg-[#0e1424] border border-white/5 shadow-lg\">\n"
                "        <span class=\"text-xs text-slate-400\">Energía por Token</span>\n"
                "        <div class=\"text-2xl font-bold text-emerald-300 mt-1\">0.024 J</div>\n"
                "        <span class=\"text-[10px] text-emerald-400\">71% ahorro de consumo</span>\n"
                "      </div>\n"
                "    </div>\n\n"
                "    <!-- Chart Area -->\n"
                "    <div class=\"p-5 rounded-2xl bg-[#0e1424] border border-white/5 shadow-lg\">\n"
                "      <h2 class=\"text-sm font-bold text-white mb-4\">Actividad Neural en Tiempo Real</h2>\n"
                "      <div class=\"h-64\">\n"
                "        <canvas id=\"chartActivity\"></canvas>\n"
                "      </div>\n"
                "    </div>\n"
                "  </div>\n\n"
                "  <script>\n"
                "    lucide.createIcons();\n"
                "    const ctx = document.getElementById('chartActivity').getContext('2d');\n"
                "    const chart = new Chart(ctx, {\n"
                "      type: 'line',\n"
                "      data: {\n"
                "        labels: ['0s', '5s', '10s', '15s', '20s', '25s', '30s', '35s', '40s'],\n"
                "        datasets: [{\n"
                "          label: 'Inferencia Ternaria (TPS)',\n"
                "          data: [42, 48, 55, 62, 59, 64, 58, 67, 72],\n"
                "          borderColor: '#00f0ff',\n"
                "          backgroundColor: 'rgba(0, 240, 255, 0.1)',\n"
                "          fill: true,\n"
                "          tension: 0.4\n"
                "        }]\n"
                "      },\n"
                "      options: {\n"
                "        responsive: true,\n"
                "        maintainAspectRatio: false,\n"
                "        scales: {\n"
                "          x: { grid: { color: 'rgba(255, 255, 255, 0.05)' }, ticks: { color: '#94a3b8' } },\n"
                "          y: { grid: { color: 'rgba(255, 255, 255, 0.05)' }, ticks: { color: '#94a3b8' } }\n"
                "        }\n"
                "      }\n"
                "    });\n"
                "  </script>\n"
                "</body>\n"
                "</html>\n"
                "```\n\n"
                "Puedes editar el HTML/JS en la pestaña **'Código'** o exportarlo como un proyecto ZIP para usarlo en producción."
            )

        # 4. Interactive 2D Math Plot / Function Visualizer
        if any(w in p_lower for w in ["grafica", "gráfica", "chart", "2d", "plot", "matematica", "matemática", "funcion", "función", "datos"]):
            return (
                "### 📊 Gráfica 2D Interactiva de Funciones Matemáticas // Chart.js & Canvas\n\n"
                "He generado un trazador matemático interactivo en 2D que permite explorar curvas y armónicos en tiempo real:\n\n"
                "```html\n"
                "<!DOCTYPE html>\n"
                "<html lang=\"es\">\n"
                "<head>\n"
                "  <meta charset=\"UTF-8\" />\n"
                "  <script src=\"https://cdn.tailwindcss.com\"></script>\n"
                "  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n"
                "</head>\n"
                "<body class=\"bg-[#06080f] text-slate-100 p-5 font-mono\">\n"
                "  <div class=\"max-w-3xl mx-auto space-y-4\">\n"
                "    <div class=\"flex justify-between items-center bg-[#0d121f] p-4 rounded-xl border border-cyan-500/30\">\n"
                "      <span class=\"font-bold text-cyan-300 text-sm\">📈 Función Armónica: f(x) = sin(x) · cos(x/2)</span>\n"
                "      <span class=\"text-xs text-slate-400\">Dominio: [-2π, 2π]</span>\n"
                "    </div>\n"
                "    <div class=\"h-80 bg-[#0d121f] p-4 rounded-xl border border-white/5 shadow-xl\">\n"
                "      <canvas id=\"mathCanvas\"></canvas>\n"
                "    </div>\n"
                "  </div>\n\n"
                "  <script>\n"
                "    const ctx = document.getElementById('mathCanvas').getContext('2d');\n"
                "    const labels = [];\n"
                "    const dataSin = [];\n"
                "    const dataHarmonic = [];\n"
                "    for (let x = -6.28; x <= 6.28; x += 0.25) {\n"
                "      labels.push(x.toFixed(2));\n"
                "      dataSin.push(Math.sin(x));\n"
                "      dataHarmonic.push(Math.sin(x) * Math.cos(x * 0.5));\n"
                "    }\n\n"
                "    new Chart(ctx, {\n"
                "      type: 'line',\n"
                "      data: {\n"
                "        labels,\n"
                "        datasets: [\n"
                "          { label: 'f(x) Armónica', data: dataHarmonic, borderColor: '#00f0ff', backgroundColor: 'rgba(0, 240, 255, 0.15)', fill: true, tension: 0.3 },\n"
                "          { label: 'sin(x)', data: dataSin, borderColor: '#a855f7', borderDash: [5, 5], tension: 0.3 }\n"
                "        ]\n"
                "      },\n"
                "      options: {\n"
                "        responsive: true,\n"
                "        maintainAspectRatio: false,\n"
                "        scales: {\n"
                "          x: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } },\n"
                "          y: { grid: { color: 'rgba(255,255,255,0.05)' }, ticks: { color: '#94a3b8' } }\n"
                "        }\n"
                "      }\n"
                "    });\n"
                "  </script>\n"
                "</body>\n"
                "</html>\n"
                "```\n\n"
                "Puedes inspeccionar cada punto pasando el cursor por encima o abrir la pestaña **'Código'** para modificar la ecuación matemática."
            )

        # 5. Interactive WebAudio Synthesizer
        if any(w in p_lower for w in ["audio", "sonido", "synth", "sintetizador", "onda", "webaudio"]):
            return (
                "### 🎵 Sintetizador Armónico & Analizador FFT en Vivo // WebAudio API\n\n"
                "He construido un sintetizador de audio interactivo con osciladores polifónicos y analizador de frecuencias en tiempo real:\n\n"
                "```html\n"
                "<!DOCTYPE html>\n"
                "<html lang=\"es\">\n"
                "<head>\n"
                "  <meta charset=\"UTF-8\" />\n"
                "  <script src=\"https://cdn.tailwindcss.com\"></script>\n"
                "</head>\n"
                "<body class=\"bg-[#080a14] text-slate-100 p-6 font-mono\">\n"
                "  <div class=\"max-w-md mx-auto p-6 rounded-2xl bg-[#0e1322] border border-cyan-500/30 shadow-2xl space-y-4 text-center\">\n"
                "    <h2 class=\"text-base font-bold text-cyan-300\">🎵 Sintetizador Cuántico 432 Hz</h2>\n"
                "    <p class=\"text-xs text-slate-400\">Afinación pitagórica con modulación de envolvente</p>\n"
                "    <canvas id=\"spectrum\" width=\"380\" height=\"120\" class=\"w-full rounded-xl bg-black border border-white/10\"></canvas>\n"
                "    <div class=\"flex justify-center gap-3 pt-2\">\n"
                "      <button id=\"btn-play\" class=\"px-6 py-2.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold shadow-lg shadow-cyan-500/20\">▶ Reproducir</button>\n"
                "      <button id=\"btn-stop\" class=\"px-6 py-2.5 rounded-xl bg-rose-500/20 text-rose-300 border border-rose-500/40 hover:bg-rose-500/30 font-bold\">⏹ Detener</button>\n"
                "    </div>\n"
                "  </div>\n\n"
                "  <script>\n"
                "    let audioCtx, osc, analyser, animId;\n"
                "    const canvas = document.getElementById('spectrum');\n"
                "    const ctx = canvas.getContext('2d');\n\n"
                "    document.getElementById('btn-play').addEventListener('click', () => {\n"
                "      if (audioCtx) return;\n"
                "      audioCtx = new (window.AudioContext || window.webkitAudioContext)();\n"
                "      osc = audioCtx.createOscillator();\n"
                "      const gain = audioCtx.createGain();\n"
                "      analyser = audioCtx.createAnalyser();\n"
                "      analyser.fftSize = 64;\n\n"
                "      osc.type = 'sine';\n"
                "      osc.frequency.setValueAtTime(432, audioCtx.currentTime);\n"
                "      gain.gain.setValueAtTime(0.15, audioCtx.currentTime);\n\n"
                "      osc.connect(gain);\n"
                "      gain.connect(analyser);\n"
                "      analyser.connect(audioCtx.destination);\n"
                "      osc.start();\n"
                "      drawSpectrum();\n"
                "    });\n\n"
                "    document.getElementById('btn-stop').addEventListener('click', () => {\n"
                "      if (!audioCtx) return;\n"
                "      osc.stop();\n"
                "      audioCtx.close();\n"
                "      audioCtx = null;\n"
                "      cancelAnimationFrame(animId);\n"
                "      ctx.clearRect(0, 0, canvas.width, canvas.height);\n"
                "    });\n\n"
                "    function drawSpectrum() {\n"
                "      animId = requestAnimationFrame(drawSpectrum);\n"
                "      const bufferLength = analyser.frequencyBinCount;\n"
                "      const dataArray = new Uint8Array(bufferLength);\n"
                "      analyser.getByteFrequencyData(dataArray);\n"
                "      ctx.fillStyle = '#000000';\n"
                "      ctx.fillRect(0, 0, canvas.width, canvas.height);\n"
                "      const barWidth = (canvas.width / bufferLength) * 2;\n"
                "      let x = 0;\n"
                "      for (let i = 0; i < bufferLength; i++) {\n"
                "        const barHeight = dataArray[i] / 2;\n"
                "        ctx.fillStyle = '#00f0ff';\n"
                "        ctx.fillRect(x, canvas.height - barHeight, barWidth, barHeight);\n"
                "        x += barWidth + 2;\n"
                "      }\n"
                "    }\n"
                "  </script>\n"
                "</body>\n"
                "</html>\n"
                "```\n\n"
                "Pulsa **'Reproducir'** en la vista previa para activar el motor de síntesis de audio."
            )

        # 6. Python / Backend Program
        if any(w in p_lower for w in ["python", "algoritmo", "script", "backend"]):
            return (
                "### 🐍 Programa Python 3 Optimizado // Host M1\n\n"
                "Aquí tienes un programa completo en Python listo para ejecutarse en el sandbox nativo de tu equipo:\n\n"
                "```python\n"
                "# Algoritmo de Inferencia y Simulación de Pesos Ternarios 1.58-Bit\n"
                "import math\n"
                "import time\n\n"
                "class BitNetLayer:\n"
                "    def __init__(self, in_features: int, out_features: int):\n"
                "        self.in_features = in_features\n"
                "        self.out_features = out_features\n"
                "        # Pesos ternarios {-1, 0, 1}\n"
                "        self.weights = [[(i + j) % 3 - 1 for j in range(out_features)] for i in range(in_features)]\n\n"
                "    def forward(self, x: list[float]) -> list[float]:\n"
                "        # En 1.58b, MatMul se convierte en acumulación de sumas y restas\n"
                "        outputs = [0.0] * self.out_features\n"
                "        for j in range(self.out_features):\n"
                "            acc = 0.0\n"
                "            for i in range(self.in_features):\n"
                "                w = self.weights[i][j]\n"
                "                if w == 1:\n"
                "                    acc += x[i]\n"
                "                elif w == -1:\n"
                "                    acc -= x[i]\n"
                "            outputs[j] = math.tanh(acc * 0.1)\n"
                "        return outputs\n\n"
                "if __name__ == '__main__':\n"
                "    start = time.perf_counter()\n"
                "    layer = BitNetLayer(in_features=64, out_features=16)\n"
                "    sample_input = [math.sin(i * 0.1) for i in range(64)]\n"
                "    result = layer.forward(sample_input)\n"
                "    elapsed = (time.perf_counter() - start) * 1000\n"
                "    print(f'✅ Capa BitNet 1.58b ejecutada exitosamente')\n"
                "    print(f'⚡ Tiempo de pase hacia adelante: {elapsed:.3f} ms')\n"
                "    print(f'📊 Salida ternaria (primeros 5 valores): {[round(v, 4) for v in result[:5]]}')\n"
                "```\n\n"
                "Pulsa **'Ejecutar'** para correr el programa en el runtime del sistema."
            )

        # 7. Identity Queries
        if any(w in p_lower for w in ["cual es mi nombre", "cómo me llamo", "quién soy", "quien soy yo"]):
            return (
                f"Tu nombre es **{self.user_identity['name']}**.\n\n"
                f"- **Usuario en macOS**: `{self.user_identity['username']}`\n"
                f"- **Equipo**: `{self.user_identity['host']}` ({self.user_identity['device']})\n"
                f"- **Rol**: Eres el creador y arquitecto del ecosistema **StarSeed OS**, **StarSeed Nexus** y de esta plataforma de IA de 1.58 bits (**Astraura**)."
            )

        # 8. General Interactive Multi-Tool Fallback with Live Canvas & Code
        return (
            f"### ⚡ Entorno Visual & Aplicación Interactiva // StarSeed OS 1.58-Bit\n\n"
            f"He preparado un entorno interactivo completo para tu consulta: **«{prompt}»**.\n\n"
            f"Incluye vista previa visual en vivo, editor multi-archivo, emulador responsive y descarga en ZIP:\n\n"
            f"```html\n"
            f"<!DOCTYPE html>\n"
            f"<html lang=\"es\">\n"
            f"<head>\n"
            f"  <meta charset=\"UTF-8\" />\n"
            f"  <title>Astraura Interactive Runtime</title>\n"
            f"  <script src=\"https://cdn.tailwindcss.com\"></script>\n"
            f"  <script src=\"https://unpkg.com/lucide@latest\"></script>\n"
            f"</head>\n"
            f"<body class=\"bg-[#080a14] text-slate-100 font-sans p-6\">\n"
            f"  <div class=\"max-w-2xl mx-auto p-6 rounded-2xl bg-[#0e1322] border border-cyan-500/30 shadow-2xl space-y-4\">\n"
            f"    <div class=\"flex items-center gap-3 pb-3 border-b border-white/10\">\n"
            f"      <div class=\"p-2.5 rounded-xl bg-cyan-500/20 text-cyan-300 border border-cyan-500/40\">\n"
            f"        <i data-lucide=\"sparkles\" class=\"w-5 h-5\"></i>\n"
            f"      </div>\n"
            f"      <div>\n"
            f"        <h2 class=\"text-sm font-bold text-white\">Programa Interactivo // Astraura 1.58-Bit</h2>\n"
            f"        <p class=\"text-xs text-slate-400\">Generado dinámicamente con Tailwind CSS y componentes interactivos</p>\n"
            f"      </div>\n"
            f"    </div>\n\n"
            f"    <div class=\"space-y-2\">\n"
            f"      <p class=\"text-xs text-slate-300 leading-relaxed\">Instrucción procesada: <span class=\"text-cyan-300 font-mono\">«{prompt}»</span></p>\n"
            f"      <div class=\"flex gap-2 pt-2\">\n"
            f"        <button onclick=\"alert('⚡ Astraura 1.58b ejecutando en tiempo real')\" class=\"px-4 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-bold text-xs shadow-lg shadow-cyan-500/20\">\n"
            f"          Probar Interacción\n"
            f"        </button>\n"
            f"      </div>\n"
            f"    </div>\n"
            f"  </div>\n\n"
            f"  <script>\n"
            f"    lucide.createIcons();\n"
            f"  </script>\n"
            f"</body>\n"
            f"</html>\n"
            f"```\n\n"
            f"Puedes probar la interfaz en **'Vista Previa'**, editar el código en **'Código'**, expandirla a pantalla completa o descargarla como archivo `.zip`."
        )

reasoner = LogicalReasoner()
